version: "2.1"
# passwords: pwgen -sA 32
# maintenance:
# influx -database telegraf1 -username masysmareader -password ...
services:
  grafana:
    image: grafana/grafana:7.0.3
    mem_limit: 50m
    restart: unless-stopped
    ports:
      - 0.0.0.0:3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=masysma
      - GF_SECURITY_ADMIN_PASSWORD
      - MASYSMAREADER_PASSWORD
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning:ro
      #- /home/linux-fan/docker-grafana:/var/lib/grafana
  influxdb:
    # -alpine version not available on armhf...
    image: influxdb:1.8
    mem_limit: 300m
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:8086:8086
    #volumes:
      #- /home/linux-fan/docker-influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf1
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      # documentation on this being optional is wrong, see
      # -> https://github.com/influxdata/influxdata-docker/issues/224
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_WRITE_USER=masysmawriter
      - INFLUXDB_WRITE_USER_PASSWORD
      - INFLUXDB_READ_USER=masysmareader
      - INFLUXDB_READ_USER_PASSWORD
  telegraf-iconqualmon:
    mem_limit: 50m
    # -alpine version not available on armhf...
    image: telegraf:1.14
    restart: unless-stopped
    environment:
      - MASYSMAWRITER_PASSWORD
    volumes:
      - ./iconqualmon/telegraf.conf:/etc/telegraf/telegraf.conf:ro
