{
 "title": "Ma_Sys.ma Internet Connection",
 "tags": [ "masysma" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"maximum_response_ms\") FROM \"ping\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "resultcode",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"result_code\") FROM \"ping\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping www.microsoft.com Hist",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "microsoft",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"maximum_response_ms\") FROM \"ping\" WHERE url = 'www.microsoft.com' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping masysma.lima-city.de Hist",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "masysma.lima-city.de",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT max(\"maximum_response_ms\") FROM \"ping\" WHERE url = 'masysma.lima-city.de' AND $timeFilter GROUP BY time($__interval) fill(null) ",
     "select": [
      [
       { "params": [ "maximum_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Response Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "response",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT max(\"result_code\") FROM \"http_response\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time masysma.lima-city.de",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      {
       "key": "server",
       "operator": "=",
       "value": "https://masysma.lima-city.de/31/web_main.xhtml"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Time www.telekom.de",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://www.telekom.de/start" }
     ]
    }
   ]
  },
  {
   "title": "masysma.lima-city.de content match",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "alias": "match",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT COUNT(\"result_code\") FROM \"http_response\" WHERE \"response_string_match\" = 1 AND $timeFilter",
     "select": [
      [
       { "params": [ "response_string_match" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "mismatch",
     "measurement": "http_response",
     "query": "SELECT COUNT(\"result_code\") FROM \"http_response\" WHERE (\"result_code\" <> 0 OR \"response_string_match\"  = 0) AND \"server\" = 'https://masysma.lima-city.de/31/web_main.xhtml' AND $timeFilter",
     "select": [
      [
       { "params": [ "response_string_match" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet losses",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT COUNT(\"result_code\") FROM \"ping\" WHERE (\"percent_packet_loss\" > 0 OR \"result_code\" = 1) AND $timeFilter GROUP BY \"url\" fill(none)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "www.microsoft.com" }
     ]
    }
   ]
  },
  {
   "title": "Packet losses",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT COUNT(\"result_code\") FROM \"http_response\" WHERE (http_response_code <> 200 OR response_string_match = 0 OR result_code <> 0) AND $timeFilter GROUP BY \"server\";",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "www.microsoft.com" }
     ]
    }
   ]
  }
 ]
}